/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Splash;

import Formularios.Principal;
import UpperEssential.UpperEssentialLookAndFeel;
import com.sun.awt.AWTUtilities;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Alex
 */
public class Frame extends javax.swing.JFrame {

    private Timer timer;
    private ActionListener actLis;
    
    public Frame() {
        
        actLis = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                if (jProgressBar1.getValue() < 100)
                {
                    jProgressBar1.setValue(jProgressBar1.getValue()+1);
                    //Mostramos el % de carga del progressbar.
                    jProgressBar1.setStringPainted(true);
                }else{
                    timer.stop();
                    //System.out.println("Ha terminado el progreso.");
                    dispose();
                    
                    //Mostramos la interfaz principal de la aplicacion.
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                        public void run() {
                                try {
                                    new Principal().setVisible(true);
                                    UIManager.setLookAndFeel(new UpperEssentialLookAndFeel("C:\\Users\\Alex\\Documents\\NetBeansProjects\\SSING_2\\Librerias\\SSING4.theme"));
                                }catch (UnsupportedLookAndFeelException ex) 
                                {
                                    System.out.print(ex);
                                }
                        }
                    });
                }
            }
        } ;
        timer = new Timer (5, actLis); // el valor son milisegundos (ms)
        initComponents();
        timer.start();
        //Colocamos el splash en el centro de la pantalla.
        this.setLocationRelativeTo(null);
        //Le da la opacidad al logotipo del splash en formato PNG
        AWTUtilities.setWindowOpaque(this, false);
        //dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage( new ImageIcon(getClass().getResource("/logotipo/fingerprint10.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(null);

        jProgressBar1.setForeground(new java.awt.Color(130, 177, 255));
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(40, 130, 180, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logotipo/fingerprint10.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 256, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}