-- MySQL Script generated by MySQL Workbench
-- 10/21/15 23:47:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ServicioIng
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ServicioIng
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ServicioIng` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ServicioIng` ;

-- -----------------------------------------------------
-- Table `ServicioIng`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`Profesor` (
  `IdProfesor` INT NOT NULL AUTO_INCREMENT,
  `HuellaProfesor` LONGBLOB NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Celular` INT NULL,
  PRIMARY KEY (`IdProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`Usuario` (
  `IdPrestador` INT NOT NULL AUTO_INCREMENT,
  `HuellaPrestador` LONGBLOB NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Tipo` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdPrestador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`Material` (
  `IdMaterial` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Band` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`Prestamo` (
  `IdProfesor` INT NOT NULL,
  `IdMaterial` INT NOT NULL,
  `IdPrestador` INT NOT NULL,
  `Fecha_Hora` DATE NOT NULL,
  INDEX `IdMaterial_idx` (`IdMaterial` ASC),
  INDEX `IdPrestador_idx` (`IdPrestador` ASC),
  PRIMARY KEY (`IdProfesor`),
  CONSTRAINT `IdProfesor`
    FOREIGN KEY (`IdProfesor`)
    REFERENCES `ServicioIng`.`Profesor` (`IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdMaterial`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ServicioIng`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPrestador`
    FOREIGN KEY (`IdPrestador`)
    REFERENCES `ServicioIng`.`Usuario` (`IdPrestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng`.`Colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`Colegio` (
  `IdColegio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdColegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng`.`ColegioProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng`.`ColegioProfesor` (
  `Profesor_IdProfesor` INT NOT NULL,
  `Colegio_IdColegio` INT NOT NULL,
  PRIMARY KEY (`Profesor_IdProfesor`, `Colegio_IdColegio`),
  INDEX `fk_ColegioProfesor_Colegio1_idx` (`Colegio_IdColegio` ASC),
  CONSTRAINT `fk_ColegioProfesor_Profesor1`
    FOREIGN KEY (`Profesor_IdProfesor`)
    REFERENCES `ServicioIng`.`Profesor` (`IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ColegioProfesor_Colegio1`
    FOREIGN KEY (`Colegio_IdColegio`)
    REFERENCES `ServicioIng`.`Colegio` (`IdColegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
