-- MySQL Script generated by MySQL Workbench
-- 10/26/15 11:26:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ServicioIng2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ServicioIng2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ServicioIng2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ServicioIng2` ;

-- -----------------------------------------------------
-- Table `ServicioIng2`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`Profesor` (
  `IdProfesor` INT NOT NULL AUTO_INCREMENT,
  `HuellaProfesor` LONGBLOB NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Celular` INT NULL,
  PRIMARY KEY (`IdProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`Usuario` (
  `IdPrestador` INT NOT NULL AUTO_INCREMENT,
  `HuellaPrestador` LONGBLOB NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Tipo` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdPrestador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng2`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`Material` (
  `IdMaterial` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Band` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng2`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`Prestamo` (
  `IdPrestamo` INT NOT NULL AUTO_INCREMENT,
  `Profesor_IdProfesor` INT NOT NULL,
  `Material_IdMaterial` INT NOT NULL,
  `Usuario_IdPrestador` INT NOT NULL,
  `Fecha_Entrega` VARCHAR(10) NOT NULL,
  `Hora_Entrega` VARCHAR(10) NOT NULL,
  `Fecha_Recibo` VARCHAR(10) NULL,
  `Hora_Recibo` VARCHAR(10) NULL,
  INDEX `IdMaterial_idx` (`Material_IdMaterial` ASC),
  INDEX `IdPrestador_idx` (`Usuario_IdPrestador` ASC),
  PRIMARY KEY (`IdPrestamo`),
  CONSTRAINT `IdProfesor`
    FOREIGN KEY (`Profesor_IdProfesor`)
    REFERENCES `ServicioIng2`.`Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IdMaterial`
    FOREIGN KEY (`Material_IdMaterial`)
    REFERENCES `ServicioIng2`.`Material` (`IdMaterial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IdPrestador`
    FOREIGN KEY (`Usuario_IdPrestador`)
    REFERENCES `ServicioIng2`.`Usuario` (`IdPrestador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng2`.`Colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`Colegio` (
  `IdColegio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdColegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServicioIng2`.`ColegioProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ServicioIng2`.`ColegioProfesor` (
  `Profesor_IdProfesor` INT NOT NULL,
  `Colegio_IdColegio` INT NOT NULL,
  PRIMARY KEY (`Profesor_IdProfesor`, `Colegio_IdColegio`),
  INDEX `fk_ColegioProfesor_Colegio1_idx` (`Colegio_IdColegio` ASC),
  CONSTRAINT `fk_ColegioProfesor_Profesor1`
    FOREIGN KEY (`Profesor_IdProfesor`)
    REFERENCES `ServicioIng2`.`Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ColegioProfesor_Colegio1`
    FOREIGN KEY (`Colegio_IdColegio`)
    REFERENCES `ServicioIng2`.`Colegio` (`IdColegio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
